server:
  port: 48081
  servlet:
    context-path: /sanwei

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sanwei_cli_dev?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: cy1959970441